// <auto-generated /> // EF Core tarafından otomatik oluşturuldu

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Data;

#nullable disable

namespace TaskFlow.Migrations;

[DbContext(typeof(ApplicationDbContext))] // Bu migration'ın DbContext'i
[Migration("20260819132219_InitialCreate")] // Migration bilgisi
partial class InitialCreate // Modelin migration'daki hali
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11"); // EF Core sürümü

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder); // ID otomatik artar

        modelBuilder.Entity("TaskFlow.Models.TaskItem", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int"); // ID

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("nvarchar(max)"); // Açıklama

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("nvarchar(max)"); // Başlık

            b.HasKey("Id"); // Primary Key

            b.ToTable("Tasks"); // Tasks tablosu
        });
    }
}