services:
  taskflow:
    image: taskflow
    restart: unless-stopped
    build:
      context: .
      dockerfile: TaskFlow/Dockerfile
    ports:
      - "5070:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=TaskFlowDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
      Jwt__Key: ${JWT_KEY}
      Database__ApplyMigrations: "true"
      Gmail__Address: ${GMAIL_ADDRESS:-}
      Gmail__AppPassword: ${GMAIL_APP_PASSWORD:-}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - taskflow_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  taskflow_sql_data:
